[build]
  command = "vite build"  # Adjust to match your frontend build command
  publish = "Frontend/Frontend/build"  # Adjust to match your frontend build output directory

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
